### ISSUE TITLE
floats used several times

### ISSUE THREAD

**Issue by ghost** [Newer-Team/NewerSMBDS#1]
Due to the usage of float in several places, the compiler generates __aeabi helpers to emulate IEEE floating point behaviour in software. 

Is this intended? It seems like it makes the code slower and inconsistent.

**Comment by RicBent** [comment]
I remember that we aware of that. I think we just replaced floats where it was critical but didn't bother to change it everywhere when we found out.

**Comment by skawo** [comment]
Yeah, sorry; we would have cleaned that up, but first it was a rush to release the game and then we just didn't :/

**Comment by RoadrunnerWMC** [comment]
As with many things, it's a tradeoff between runtime performance and ease of programming. Most of the custom sprites don't use any floats, and the game doesn't have any real issues with lagging as far as I'm aware, so I'd say it's perfectly fine from a pragmatic standpoint.
