### ISSUE TITLE
How to i apply the hack files to my New Super Mario Bros. USA NDS rom?

### ISSUE THREAD

**Issue by JohnsonRex** [Newer-Team/NewerSMBDS#3]
NSMB Editor 5 Hack Patch: I want to use the following for my W.I.P NDS rom hack, More Awesome Super Mario Bros, for New Super Mario Bros DS. How do i use them?

https://github.com/Newer-Team/NewerSMBDS/tree/main/patches
https://github.com/Newer-Team/NewerSMBDS/tree/main/UNUSED
https://github.com/Newer-Team/NewerSMBDS/tree/main/Assembly

I have to credit Newer Team if i use them in my NDS hack!

**Comment by RicBent** [comment]
Please refer to the provided [readme](https://github.com/Newer-Team/NewerSMBDS/blob/main/README.md).

The described process will apply all the patches to the overlays etc and will apply all the code modifications from the `Assembly` folder.

The code from `UNUSED` will obviously not be applied unless you copy whatever you want from there to the proper places in `Assembly`. Obviously stuff in there may be broken in all sorts of ways.
